### ISSUE TITLE
Plan CRUD functionality on front-end

### ISSUE THREAD

**Issue by dopecello** [JaxTurboNerd/Jax-Pet-Names#6]
Just reading off the express server API calls, there is full CRUD functionality. 

Right now, we can generate names over and over and set a Male or Female state when generating name.

### Update Use Case:

WHEN I generate a name for my pet,
THEN I have a menu that comes up asking if I want to contribute names of my own
WHEN I submit a pet name to the database
THEN the name is auto-capitalized for the first letter, and is submitted for review. (step might not be necessary)

WHEN I see a name I like
THEN I can give it a like

(Could have a most popular names sidebar in the top right or right hand side of the app)

### Delete Use Case:

IF I see a name that I don't like.
THEN I can vote to have it removed, especially if it's inappropriate or spelled horribly.
WHEN a name reaches 5 votes
THEN the name is permanently removed from the database. Also, can never be submitted again

Just some ideas to fully utilize the API and also keep the app fun to make. Would love to hear other ideas

--- dopecello

**Comment by JaxTurboNerd** [comment]
Full CRUD functionality was implemented on the back end.  Only partial use of CRUD functions will be required on the front end.
